apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - location: dev
      - location: staging
      - location: analysis
      - location: prod-region1
      - location: prod-region2
  template:
    metadata:
      name: 'guestbook-{{.location}}'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{ .location }}
    spec:
      project: default
      source:
        repoURL: https://github.com/rohitasva/kargo-simple.git
        targetRevision: HEAD
        path: 'env/{{.location}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'guestbook-{{.location}}'
      syncPolicy:
        automated:
          selfHeal: true
