# This is a sample analysis template that uses the PokeAPI to
# check the base experience of a Pokemon is under threshold.
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pokemon-xp
  namespace: kargo-simple
spec:
  args:
  - name: service-name
    value: guestbook-simple.guestbook-simple-analysis.svc.cluster.local
  metrics:
  - name: pokemon-xp
    interval: 5s
    count: 5
    successCondition: result == "80"
    failureLimit: 3
    provider:
      web:
        url: http://{{args.service-name}}/env
        jsonPath: "{$.GUESTBOOK_SIMPLE_PORT_80_TCP_PORT}"
