apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    analysisTemplates:
    - name: pokemon-xp
    args:
    - name: service-name
      value: guestbook-simple.guestbook-staging.svc.cluster.local
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: analysis
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    analysisTemplates:
    - name: pokemon-xp
    args:
    - name: service-name
      value: guestbook-simple.guestbook-analysis.svc.cluster.local
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-region1
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - analysis
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-region2
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - analysis
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
