apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/rohitasva/kargo-simple.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-{{base .path.path}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{base .path.path}}
    spec:
      project: default
      source:
        repoURL: https://github.com/rohitasva/kargo-simple.git
        targetRevision: env/{{base .path.path}}
        path: './'
      destination:
        server: 'http://cluster-local:8001'
        namespace: guestbook-{{base .path.path}}
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
