apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/rohitasva/kargo-simple.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-'{{.path.basename}}'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:'{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rohitasva/kargo-simple.git
        targetRevision: env/'{{.path.basename}}'
        path: './'
      destination:
        server: http://cluster-local:8001
        namespace: guestbook-'{{.path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
